apiVersion: v1
kind: Service
metadata:
  name: seamarg-backend
  namespace: seamarg
  labels:
    app.kubernetes.io/name: seamarg-backend
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: seamarg-backend
  ports:
    - name: http
      port: 80
      targetPort: http
